// ChatAppClient/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';
import { SignalRService } from '../../services/signalr.service';
import { PeerService } from '../../services/peer.service'; // Import PeerService

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  errorMessage: string | null = null;

  constructor(
    private authService: AuthService,
    private router: Router,
    private signalRService: SignalRService, // Inject SignalRService
    private peerService: PeerService // Inject PeerService
  ) {}

  onLogin(): void {
    this.authService.login(this.username, this.password).subscribe({
      next: async (response) => {
        // Lưu thông tin vào localStorage
        localStorage.setItem('userId', response.id);
        localStorage.setItem('token', response.token);
        localStorage.setItem('userAvatar', response.avatar);
        localStorage.setItem('role', response.role); // Lưu role của người dùng

        console.log("Login successful");
        console.log("User ID:", response.id);
        console.log("Token:", response.token);

        // Kết nối SignalR sau khi đăng nhập thành công
        await this.signalRService.startConnection();

        // Khởi tạo Peer và đăng ký peerId sau khi đăng nhập thành công
        this.peerService.initializePeer();

        // Điều hướng dựa trên role của người dùng
        if (response.role === 'Admin') {
          this.router.navigate(['/admin']);
        } else if (response.role === 'User') {
          this.router.navigate(['/chats']);
        } else {
          // Nếu role không xác định, có thể chuyển đến một trang mặc định hoặc trang lỗi
          this.router.navigate(['/login']);
        }
      },
      error: (error) => {
        console.error("Login failed", error);

        // Hiển thị thông báo lỗi nếu có
        this.errorMessage = error.error.message || "Login failed. Please check your credentials and try again.";
      }
    });
  }
}

<div class="row d-flex justify-content-center align-items-center" style="height: 98vh;">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <h3>Login</h3>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label>Name</label>
          <input [(ngModel)]="name" type="text" class="form-control" placeholder="Enter your name">
        </div>
        <div class="form-group mt-2">
          <label>Password</label>
          <input [(ngModel)]="password" type="password" class="form-control" placeholder="Enter your password">
        </div>
        <div class="form-group mt-2">
          <button class="btn btn-dark w-100" (click)="login()">Log in</button>
        </div>
        <div class="form-group mt-2">
          <a href="/register">Register</a>
        </div>
      </div>
    </div>
  </div>
</div>

// src/pages/login/login.component.ts
import React, { useState } from 'react';
import { View, Text, TextInput, Button, Alert } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import AuthService from '~/services/auth.service';
import AsyncStorage from '@react-native-async-storage/async-storage';
// import SignalRService from '~/services/signalr.service';
export default function LoginComponent(account: string, pass: string) {
  const [username, setUsername] = useState<string>(account);
  const [password, setPassword] = useState<string>(pass);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const navigation = useNavigation();
  // const signalRService = new SignalRService();
  // const peerService = new PeerService();

  const onLogin = async () => {
    try {
      const response = await AuthService.login(username, password);

      // Save info to AsyncStorage
      await AsyncStorage.setItem('userId', response.id);
      await AsyncStorage.setItem('token', response.token);
      await AsyncStorage.setItem('userAvatar', response.avatar);
      await AsyncStorage.setItem('role', response.role);

      console.log('Login successful');
      console.log('User ID:', response.id);
      console.log('Token:', response.token);

      // Start SignalR connection after login
      // await signalRService.startConnection();

      // Navigate based on user role
      // if (response.role === 'Admin') {
      //   navigation.navigate('AdminScreen');
      // } else if (response.role === 'User') {
      //   navigation.navigate('ChatScreen');
      // } else {
      //   navigation.navigate('LoginScreen');
      // }
    } catch (error: any) {
      console.error('Login failed', error);
      setErrorMessage(error.message || 'Login failed. Please check your credentials and try again.');
      Alert.alert('Login Error', errorMessage || 'An error occurred');
    }
  };

  onLogin();

  // return (
  //   <View style={{ padding: 16 }}>
  //     <Text>Login</Text>
  //     <TextInput
  //       placeholder="Username"
  //       value={username}
  //       onChangeText={setUsername}
  //       style={{ borderBottomWidth: 1, marginBottom: 16 }}
  //     />
  //     <TextInput
  //       placeholder="Password"
  //       value={password}
  //       onChangeText={setPassword}
  //       secureTextEntry
  //       style={{ borderBottomWidth: 1, marginBottom: 16 }}
  //     />
  //     {errorMessage && <Text style={{ color: 'red' }}>{errorMessage}</Text>}
  //     <Button title="Login" onPress={onLogin} />
  //   </View>
  // );
  return (
    {}
  );
};
