// src/pages/login/login.component.ts
import React, { useState } from 'react';
import { View, Text, TextInput, Button, Alert } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import AuthService from '~/services/auth.service';
import AsyncStorage from '@react-native-async-storage/async-storage';
// import SignalRService from '~/services/signalr.service';
export default function LoginComponent(account: string, pass: string) {
  const [username, setUsername] = useState<string>(account);
  const [password, setPassword] = useState<string>(pass);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const navigation = useNavigation();
  // const signalRService = new SignalRService();
  // const peerService = new PeerService();

  const onLogin = async () => {
    try {
      const response = await AuthService.login(username, password);

      // Save info to AsyncStorage
      await AsyncStorage.setItem('userId', response.id);
      await AsyncStorage.setItem('token', response.token);
      await AsyncStorage.setItem('userAvatar', response.avatar);
      await AsyncStorage.setItem('role', response.role);

      console.log('Login successful');
      console.log('User ID:', response.id);
      console.log('Token:', response.token);

      // Start SignalR connection after login
      // await signalRService.startConnection();

      // Navigate based on user role
      // if (response.role === 'Admin') {
      //   navigation.navigate('AdminScreen');
      // } else if (response.role === 'User') {
      //   navigation.navigate('ChatScreen');
      // } else {
      //   navigation.navigate('LoginScreen');
      // }
    } catch (error: any) {
      console.error('Login failed', error);
      setErrorMessage(error.message || 'Login failed. Please check your credentials and try again.');
      Alert.alert('Login Error', errorMessage || 'An error occurred');
    }
  };

  onLogin();

  // return (
  //   <View style={{ padding: 16 }}>
  //     <Text>Login</Text>
  //     <TextInput
  //       placeholder="Username"
  //       value={username}
  //       onChangeText={setUsername}
  //       style={{ borderBottomWidth: 1, marginBottom: 16 }}
  //     />
  //     <TextInput
  //       placeholder="Password"
  //       value={password}
  //       onChangeText={setPassword}
  //       secureTextEntry
  //       style={{ borderBottomWidth: 1, marginBottom: 16 }}
  //     />
  //     {errorMessage && <Text style={{ color: 'red' }}>{errorMessage}</Text>}
  //     <Button title="Login" onPress={onLogin} />
  //   </View>
  // );
  return (
    {}
  );
};

// ChatAppClientServiceExample/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  errorMessage: string | null = null;

  constructor(private authService: AuthService, private router: Router) {}

  onLogin(): void {
    this.authService.login(this.username, this.password).subscribe({
      next: (response) => {
        // Assuming response contains userId and token
        sessionStorage.setItem('userId', response.id);
        sessionStorage.setItem('token', response.token);
        sessionStorage.setItem('userAvatar', response.avatar);

        console.log("Login successful");
        console.log("User ID:", response.id);
        console.log("Token:", response.token);

        // Redirect to another page or perform other actions after successful login
        this.router.navigate(['/chats']);
      },
      error: (error) => {
        console.error("Login failed", error);
        this.errorMessage = "Login failed. Please check your credentials and try again.";
      }
    });
  }
}

<div class="login-container">
  <h2>Login</h2>
  <form (submit)="onLogin()">
    <div>
      <label for="username">Username:</label>
      <input type="text" id="username" [(ngModel)]="username" name="username" required>
    </div>
    <div>
      <label for="password">Password:</label>
      <input type="password" id="password" [(ngModel)]="password" name="password" required>
    </div>
    <button type="submit">Login</button>
  </form>

  <div *ngIf="errorMessage" class="error-message">
    {{ errorMessage }}
  </div>

  <div class="forgot-password-link">
    <a routerLink="/forgot-password">Forgot Password?</a>
  </div>
</div>
